### ISSUE TITLE
tsne gives nan

### ISSUE THREAD

**Issue by hjenryin** [mxl1990/tsne-pytorch#5]
Here is an example:
```
from tsne_torch import TorchTSNE as TSNE
# from sklearn.manifold import TSNE
import torch
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt

dataset = torchvision.datasets.MNIST(root="path of the dataset",
                                     train=False,
                                     download=False,
                                     transform=transforms.ToTensor())
x = dataset.data
n = x.shape[0]
x = x.reshape(n, -1)
n0 = int(0.01 * n)
x = torch.tensor(x[:n0], dtype=torch.float32)

X_tsne = TSNE(n_components=2, perplexity=10, n_iter=250,
              verbose=True).fit_transform(x)
print(X_tsne)
```
This gives a series of ```nan```s. However, if we use _sklearn_ instead (as commented in the original code), this gives some meaningful results.

Could you please figure out why this is the case?

**Comment by mxl1990** [comment]
> Here is an example:
> 
> ```
> from tsne_torch import TorchTSNE as TSNE
> # from sklearn.manifold import TSNE
> import torch
> import torchvision
> import torchvision.transforms as transforms
> import matplotlib.pyplot as plt
> 
> dataset = torchvision.datasets.MNIST(root="path of the dataset",
>                                      train=False,
>                                      download=False,
>                                      transform=transforms.ToTensor())
> x = dataset.data
> n = x.shape[0]
> x = x.reshape(n, -1)
> n0 = int(0.01 * n)
> x = torch.tensor(x[:n0], dtype=torch.float32)
> 
> X_tsne = TSNE(n_components=2, perplexity=10, n_iter=250,
>               verbose=True).fit_transform(x)
> print(X_tsne)
> ```
> 
> This gives a series of `nan`s. However, if we use _sklearn_ instead (as commented in the original code), this gives some meaningful results.
> 
> Could you please figure out why this is the case?

Thank you for your feedback, and this case is caused by the range of input data, our script only assume input data in range [0.0, 1.0], but x value in range [0.0, 255.0], so before input, just add x = x / 255. can solve this nan problem.

**Comment by hjenryin** [comment]
It's working now. Thanks a lot!
